{{- if .Values.publicService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web-public
  labels:
    {{- include "shop.labels" (dict "root" . "component" "web") | nindent 4 }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /healthz
spec:
  type: LoadBalancer
  loadBalancerClass: service.k8s.aws/nlb
  selector:
    {{- include "shop.selectorLabels" (dict "root" . "component" "web") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
{{- end }}
